# Generated by Django 3.2.8 on 2021-10-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=10)),
                ('parent_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('self_id', models.CharField(max_length=10)),
                ('category_id', models.CharField(max_length=10)),
                ('picture', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AddIndex(
            model_name='offers',
            index=models.Index(fields=['self_id'], name='self_id_idx'),
        ),
    ]
